### ISSUE TITLE
New Token--[mapconcierge]

### ISSUE THREAD

**Issue by mapconcierge** [hotosm/oam-uploader-admin#12]
Name: mapconcierge
Email: mapconcierge@gmail.com
Location of imagery: Sagamihara, Kanagawa, Japan
Source of imagery: UAV
Short description of collection: We've taken high-resolution aerial photo by eBee drone.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@mapconcierge Just made a token and emailed it you. Let us know if any questions along the way. I will close out this ticket for now, but feel free to add a note here once it is complete with a link to your imagery on OAM.

**Comment by mapconcierge** [comment]
Thanks @smit1678 !
I've confirmed!!

**Comment by mapconcierge** [comment]
Oh, already expired ... orz

**Comment by smit1678** [comment]
@mapconcierge Just checked the settings and it shouldn't be expired. I resent you the token. Try again, if it doesn't work we'll generate a new one for you.

**Comment by mapconcierge** [comment]
Thanks! @smit1678 :-)

**Comment by mapconcierge** [comment]
Hi, @smit1678 
My token is expired, please update! Thanks!!
