### ISSUE TITLE
New Token--[mapconcierge]

### ISSUE THREAD

**Issue by mapconcierge** [hotosm/oam-uploader-admin#16]
Name: mapconcierge
Email: taichi@osmf.jp
Location of imagery: Japan
Source of imagery: My own capturing (UAV)
Short description of collection: UAV Orthophoto Imarery of Tsunami affected area and others.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@mapconcierge Did the token I sent in #12 not work?

**Comment by mapconcierge** [comment]
Many thanks!! I've done!!! :-)
<img width="996" alt="2017-09-08 18 41 56" src="https://user-images.githubusercontent.com/416977/30206253-8370787c-94c6-11e7-993f-ab07cbb5e549.png">
