### ISSUE TITLE
New Token--[NAME]

### ISSUE THREAD

**Issue by n10w84** [hotosm/oam-uploader-admin#17]
Name: Marcial Porras
Email: n10w84@gmail.com
Location of imagery: Fultierra, Sabanilla, San Jose, Costa Rica
Source of imagery: My own capturing (UAV)
Short description of collection:Orthomosaic done by UAV. Vegetable garden.
Have you received approval for making this imagery available (yes/no)?:Yes

**Comment by smit1678** [comment]
@n10w84 -- Thanks. I just sent a token to your email. Post here if any questions.
