### ISSUE TITLE
New Token--Erika Reinhardt @ Planet Labs

### ISSUE THREAD

**Issue by embreinhardt** [hotosm/oam-uploader-admin#20]
Name: Erika Reinhardt
Email: erika@planet.com
Location of imagery: Ecuador
Source of imagery: Planet Labs
Short description of collection: imagery over ecauador from 4/16-4/20/2016 for earthquake response
Have you received approval for making this imagery available (yes/no)?: Yes + all is CC-BY-SA

**Comment by cgiovando** [comment]
Sent
