### ISSUE TITLE
Upload page has a fake email address

### ISSUE THREAD

**Issue by embreinhardt** [hotosm/oam-uploader-admin#21]
The Request a Token —> Send email link on http://upload.openaerialmap.org/ goes to email@example.com

**Comment by cgiovando** [comment]
@smit1678 - can you fix that?

**Comment by smit1678** [comment]
Yeah that shouldn't be there 






On Sat, Apr 23, 2016 at 11:55 AM -0700, "Cristiano Giovando" <notifications@github.com> wrote:












@smit1678 - can you fix that?

**Comment by smit1678** [comment]
Fixed via https://github.com/hotosm/oam-uploader/commit/8c26fe67691511e552a4c15a2d27d87ae1e691d2. Points to sysadmin@hotosm.org now.
