### ISSUE TITLE
UAV imagery Carretera Puente Rio Chico

### ISSUE THREAD

**Issue by fruizc** [hotosm/oam-uploader-admin#24]
Name: Santiago Pastor
Email: voluntarios
Location of imagery: Canton Portoviejo, puente RIo Chico
Source of imagery: UAV 
Short description of collection:
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@fruizc Did you get a token sent to you?

**Comment by fruizc** [comment]
Hi!
Not yet I woil like to upload mmore iamgery from Ecaudor UAV Volunteers
Tks
fruizc

**Comment by smit1678** [comment]
Great. Just emailed you a token.
