### ISSUE TITLE
New Token--[Fredy Rivera]

### ISSUE THREAD

**Issue by humano** [hotosm/oam-uploader-admin#27]
Name: Fredy Rivera
Email: fredyrivera@openstreetmap.co
Location of imagery: Colombia
Source of imagery: AUV
Short description of collection: http://wiki.openstreetmap.org/wiki/2015_Salgar_Colombia_landslide
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@humano I sent you a token at the above email.
