### ISSUE TITLE
New Token--[Guapi]

### ISSUE THREAD

**Issue by kaxtillo** [hotosm/oam-uploader-admin#28]
Name: kaxtillo
Email: kaxtillo@gmail.com
Location of imagery: Guapi, Cauca, Colombia
Source of imagery: Universidad Nacional de Colombia
Short description of collection: Ortofotografia de la cabecera municipal de Guapi, Cauca, Colombia
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@kaxtillo Thanks. I issued and sent a token to the your email.
