### ISSUE TITLE
landslide-desmoineWA

### ISSUE THREAD

**Issue by bricker0** [hotosm/oam-uploader-admin#29]
Name: Britta Ricker
Email: brittaricker@gmail.com
Location of imagery: Des Moines, WA
Source of imagery: Phantom Vision 2+
Short description of collection: orthophoto of a landslide
Have you received approval for making this imagery available (yes/no)?:yes

**Comment by smit1678** [comment]
@bricker0 Just sent a token to the above email. Post here if any questions.
