### ISSUE TITLE
New Token--Duluth

### ISSUE THREAD

**Issue by pierotofy** [hotosm/oam-uploader-admin#32]
Name: Piero Toffanin
Email: pt@masseranolabs.com
Location of imagery: Brighton Beach, Duluth MN
Source of imagery: UAV
Short description of collection: Small areas mapped in Duluth MN
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@pierotofy -- Just sent you a token. Post here if any questions.
