### ISSUE TITLE
New Token--KennyLuk

### ISSUE THREAD

**Issue by kennyluk** [hotosm/oam-uploader-admin#36]
Name: Kenny Luk
Email: kenny {at} olgs.com
Location of imagery: Malapascua Island, Cebu, Philippines 
Source of imagery: DJI Phantom 3 Pro
Short description of collection: Coverage of about 1/5 of the island near the South
Have you received approval for making this imagery available (yes/no)?: Yes, I created and own the images

**Comment by smit1678** [comment]
@kennyluk Just emailed a token to you.
