### ISSUE TITLE
New Token--[Blake Girardot]

### ISSUE THREAD

**Issue by bgirardot** [hotosm/oam-uploader-admin#42]
Name: Blake Girardot
Email: blake.girardot@hotosm.org
Location of imagery: global
Source of imagery: LandSat8 and Sentinel2
Short description of collection: Ad hoc processing of LS and Sentinel images for various uses.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@bgirardot Sent to your email!
