### ISSUE TITLE
New Token--Oleg Seliverstov

### ISSUE THREAD

**Issue by olegseliverstov** [hotosm/oam-uploader-admin#43]
Name: Oleg Seliverstov
Email: oleg.seliverstov@gmail.com
Location of imagery: Kharkiv, Ukraine, 50.0614/35.1866
Source of imagery: Drone aerial survey
Short description of collection: Drone aerial survey of National Park
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@carto-lab You should have previously received a token via email a couple weeks ago. Can you confirm that you received it and it worked?

**Comment by carto-lab** [comment]
@smit1678 I confirm the token is received. Thank you!
