### ISSUE TITLE
New Token--Hansestadt Rostock

### ISSUE THREAD

**Issue by kvlahromei** [hotosm/oam-uploader-admin#45]
Name: Hansestadt Rostock – Kataster-, Vermessungs- und Liegenschaftsamt
Email:geodienste AT rostock.de
Location of imagery: https://www.opendata-hro.de/dataset?tags=Luftbild 
Source of imagery: aircraft
Short description of collection: Aerial imagery of the city of rostock and some surrounding areas ("Rostocker Heide")
Have you received approval for making this imagery available (yes/no)?: We approve that this datasets are licensed under CC0 1.0 thus make it available to OAM

**Comment by smit1678** [comment]
Thanks @kvlahromei. Sent a token to the email you provided.
