### ISSUE TITLE
The Moon World Landscape in Longchi, Tainan, Taiwan--[Yu-Huang Wang]

### ISSUE THREAD

**Issue by ecoinfo** [hotosm/oam-uploader-admin#48]
Name: Yu-Huang Wang
Email: yuhuangwang@gmail.com
Location of imagery: Longchi, Tainan, Taiwan
Source of imagery: Images captured using DJI Phantom 4 and processed by Pix4Dmapper Pro
Short description of collection: A spectacular Moon World Landscape in the Longchi District, Tainan City, Taiwan. This beautiful place is suffering from the great pressure of inadequate and unsustainable use, planned for the landfill site of toxic industrial waste.
Have you received approval for making this imagery available (yes/no)?: Yes

**Comment by smit1678** [comment]
Token was sent via email.
