### ISSUE TITLE
New Token--[Dan Dawson]

### ISSUE THREAD

**Issue by DanDawson** [hotosm/oam-uploader-admin#49]
Name: Dan Dawson
Email: info@ddphoto.cc
Location of imagery: Bend, OR
Source of imagery: UAS
Short description of collection: Imagery of new construction to aid with my OpenStreetMaps road creation.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@DanDawson A token has been emailed to the address you provided. Post any issues with your upload here.
