### ISSUE TITLE
New Token--[Tomasz Nycz]

### ISSUE THREAD

**Issue by merkato** [hotosm/oam-uploader-admin#50]
Name: Tomasz Nycz
Email: tomasz.merkato@gmail.com
Location of imagery: Istebna commune
Source of imagery: Drone aerial survey / OpenDroneMap processing toolchain
Short description of collection: Aerial orthophoto's of Istebna commune 
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@merkato Thanks for contributing! A token was sent to the email provided above.
