### ISSUE TITLE
New Token--Dakota Benjamin

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/oam-uploader-admin#51]
Name: Dakota Benjamin
Email: dmb2@clevelandmetroparks.com
Location of imagery: Cleveland Metroparks (various)
Source of imagery: UAS
Short description of collection: Aerial Imagery from UAS Program
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@dakotabenjamin Thanks for contributing! A token was sent to the email provided above.
