### ISSUE TITLE
New Token--[Rumicucho]

### ISSUE THREAD

**Issue by renandp11** [hotosm/oam-uploader-admin#52]
Name: Renan Davila
Email: davila.renan@gmail.com
Location of imagery: Quito, Pichincha, Ecuador
Source of imagery: UAV Inspire 1 
Short description of collection: Ecuadorian Inca ruins
Have you received approval for making this imagery available (yes/no)?: Yes, it's a tourist site (Want to load image for testing purposes)

**Comment by smit1678** [comment]
@renandp11 Thanks for contributing. A token was sent to the email you provided.
