### ISSUE TITLE
New Token--[Srimal Samansiri)

### ISSUE THREAD

**Issue by srimalsl** [hotosm/oam-uploader-admin#57]
Name: Srimal Samansiri
Email: srimalsl@yahoo.com
Location of imagery: Sri Lanka
Source of imagery: UAV Photos of various locations
Short description of collection: All the data collected for disaster management 
Have you received approval for making this imagery available (yes/no)?:Yes

**Comment by smit1678** [comment]
@srimalsl Thanks for contributing. A token was sent to the email provided. Post any questions or issues here.
