### ISSUE TITLE
Pollutant fishfarm in Taiwan

### ISSUE THREAD

**Issue by neil33533** [hotosm/oam-uploader-admin#59]
Name: NeilChang
Email: neil33533@gmail.com
Location of imagery: Taiwan
Source of imagery: Tainan Community College
Short description of collection: Pollutant fishfarm in Taiwan
Have you received approval for making this imagery available (yes/no)?: Yes
![Uploading 18339594_120300003615627806_853845313_o.jpg…]()

**Comment by smit1678** [comment]
@neil33533 Thanks for contributing! A token was sent to the email you provided. Please post any issues here in this ticket.
