### ISSUE TITLE
Expiration date field

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader-admin#6]
Set Expiration field as be a date field

![](https://api.monosnap.com/rpc/file/download?id=Wjsu95ORS3614w6heUO1zFqYrZOVj0)

cc @ricardomestre @danielfdsilva

**Comment by danielfdsilva** [comment]
The form is not entirely complete. It was left as free text just to see it working.
It will be a date string with a date picker, like the one on oam-uploader
