### ISSUE TITLE
New Token--[Aeracoop]

### ISSUE THREAD

**Issue by lotelx** [hotosm/oam-uploader-admin#61]
Name: Lot Amorós
Email: aeracoop@gmail.com
Location of imagery: La Marina, Alicante, Spain
Source of imagery: UAV
Short description of collection: Rural Area in contryside
Have you received approval for making this imagery available (yes/no)?: I made by myself, and I have permission of the owner of the terrain.

**Comment by smit1678** [comment]
@lotelx A token was sent to the email provided above. Post here if any follow up questions.
