### ISSUE TITLE
New Token--[ragnvald]

### ISSUE THREAD

**Issue by ragnvald** [hotosm/oam-uploader-admin#65]
Name: Ragnvald Larsen
Email: ragnvald@mindland.com
Location of imagery: Northern Norway
Source of imagery: UAV (Mavic Pro processed with Pix4D)
Short description of collection: Several geotiffs from an island in northern parts of Norway.
Have you received approval for making this imagery available (yes/no)?: yes - I decide this.

**Comment by smit1678** [comment]
@ragnvald A token was sent to the email you provided. Thank you for contributing!
