### ISSUE TITLE
New Token--komzpa

### ISSUE THREAD

**Issue by Komzpa** [hotosm/oam-uploader-admin#66]
Name: Darafei Praliaskouski
Email: me@komzpa.net
Location of imagery: Belarus
Source of imagery: DJI Mavic pro
Short description of collection: a set of flights around villages with Pix4D and Mavic.
Have you received approval for making this imagery available (yes/no)?: yes (I did it!)

**Comment by smit1678** [comment]
@Komzpa A token was sent to the email you provided. Reopen the ticket here if you run into any uploading issues. Thanks for contributing!
