### ISSUE TITLE
New Token--[Sergey Astakhov]

### ISSUE THREAD

**Issue by sergeyastakhov** [hotosm/oam-uploader-admin#67]
Name: Sergey Astakhov
Email: sergeyastakhov@mail.ru
Location of imagery: Russia, Saint-Petersburg https://cloud.mail.ru/public/9tum/MFCC8kwDP
Source of imagery: UAV
Short description of collection: Aerophoto from quadrocopter
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@sergeyastakhov Thanks for contributing. A token was sent to the email you provided.
