### ISSUE TITLE
New Token--[Chihhsiang Chien]

### ISSUE THREAD

**Issue by ChihHsiangChien** [hotosm/oam-uploader-admin#68]
Name: Chihhsiang Chien
Email: pancala@gmail.com
Location of imagery: Taiwan
Source of imagery: UAV Photos of various locations
Short description of collection: rivers or mountains in Taiwan
Have you received approval for making this imagery available (yes/no)?:yes

**Comment by smit1678** [comment]
@ChihHsiangChien Thank you for contributing. A token was sent to the email you provided.
