### ISSUE TITLE
New Token--[NAME]

### ISSUE THREAD

**Issue by Nemo08** [hotosm/oam-uploader-admin#69]
Name: Anatoly D
Email: bigblacklazycat@gmail.com
Location of imagery: Russia, Tambovskaya obl, Kotovsk
Source of imagery: drone
Short description of collection: Central part of Kotovsk
Have you received approval for making this imagery available (yes/no)?: no, my imaginery

**Comment by smit1678** [comment]
@Nemo08 Thanks for contributing to OpenAerialMap. A token was sent to the email provided.
