### ISSUE TITLE
New Token--[Vitali Danilovich]

### ISSUE THREAD

**Issue by danvyr** [hotosm/oam-uploader-admin#70]
Name: Vitali Danilovich
Email: danvyr@gmail.com
Location of imagery: Belarus
Source of imagery: DJI Mavic pro
Short description of collection:  a set of flights around villages with Pix4D and Mavic.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@danvyr Thanks for contributing. A token was sent to the email address provided.
