### ISSUE TITLE
New Token--trolleway

### ISSUE THREAD

**Issue by trolleway** [hotosm/oam-uploader-admin#71]
Name: trolleway
Email: trolleway@yandex.ru
Location of imagery: Moscow Oblast, http://trolleway.nextgis.com/resource/1699/display
Source of imagery: UAV DJI Phantom 3 Pro
Short description of collection: Aerophoto of Moscow area for Openstreetmap contribution
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@trolleway - Thanks for contributing. A token was sent to the email you provided.
