### ISSUE TITLE
New Token--[Thomas Starnes]

### ISSUE THREAD

**Issue by thomstarnes** [hotosm/oam-uploader-admin#72]
Name: Thomas Starnes
Email: thomas.starnes@rspb.org.uk
Location of imagery: Swindale Meadows
Source of imagery: Royal Society for the Protection of Birds
Short description of collection: Imagery from Swindale Beck in the Lake District, UK, collected on  04/05/2017 by RSPB ecologists.
Have you received approval for making this imagery available (yes/no)?: Yes

**Comment by smit1678** [comment]
@thomstarnes Thanks for contributing. A token was sent to the email you provided.
