### ISSUE TITLE
New Token--Stephen Mather

### ISSUE THREAD

**Issue by smathermather** [hotosm/oam-uploader-admin#74]
Name: Stephen Vincent Mather
Email: stephen@smathermather.com
Location of imagery: Haiti
Source of imagery: 2010 RIT WASP Flight
Short description of collection: Flight of WASP camera system and LiDAR from 21-27 January 2010.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@smathermather token in your email.
