### ISSUE TITLE
New Token--mguzelevich

### ISSUE THREAD

**Issue by mguzelevich** [hotosm/oam-uploader-admin#75]
Name: Michael Guzelevich
Email: m.guzelevich@gmail.com
Location of imagery: Belarus
Source of imagery: DJI Phantom, DJI Mavic Pro, GoPro
Short description of collection: some flies in belarus
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@mguzelevich Thank you for contributing. A token was sent to the email provided.
