### ISSUE TITLE
New Token--510 - Netherlands Red Cross

### ISSUE THREAD

**Issue by mjvanderveen** [hotosm/oam-uploader-admin#78]
Name: 510 - Netherlands Red Cross
Email: info@510.global
Location of imagery: worldwide
Source of imagery: drones
Short description of collection: through drones
Have you received approval for making this imagery available (yes/no)?: we ask for consent where possible

**Comment by smit1678** [comment]
@mjvanderveen 👍 A token was sent to the email provided.
