### ISSUE TITLE
New Token--[GlobalMedic]

### ISSUE THREAD

**Issue by francoboy7** [hotosm/oam-uploader-admin#80]
Name: Globalmedic

Email: fauclair@globalmedic.ca

Location of imagery: Barbuda Island

Source of imagery: UAV DGI Inspire 2 (drone)

Short description of collection: 

The area of Codrington
North of Airport runway
New development South of airport runway
Have you received approval for making this imagery available (yes/no)?: YES

Please note, an email was sent to : info@openaerialmap.org

**Comment by smit1678** [comment]
@francoboy7 👍  A token was sent to fauclair@globalmedic.ca. Let us know if you have any difficulties using that token. This same token can also be used for all Global Medic uploads.
