### ISSUE TITLE
Xai-Xai Cidade

### ISSUE THREAD

**Issue by Nadezhda1304** [hotosm/oam-uploader-admin#81]
Name: Identifying malarial mosquito habitats
Email: n.denbesten@futurewater.nl
Location of imagery: Xai-Xai, Gaza Province, Mozambique
Source of imagery: ThirdEye
Short description of collection: The flight was performed in February 2017, in order to analyze the potential to deploy our UAVs to map possible malarial mosquito habitats.
Have you received approval for making this imagery available (yes/no)?: y
![9_xaixai_top_view_water](https://user-images.githubusercontent.com/32359705/30964596-50bd3dc0-a452-11e7-8297-c309060369ed.png)

[http://www.thirdeyewater.com/](url)

**Comment by smit1678** [comment]
Thanks @Nadezhda1304. A token was sent to the email you provided.
