### ISSUE TITLE
New Token-Haldimand County Imagery

### ISSUE THREAD

**Issue by CanopyMappingCo** [hotosm/oam-uploader-admin#83]
Name: Matthew Davis
Email: mdavis@haldimandcounty.on.ca
Location of imagery: Haldimand County, Ontario, Canada
Source of imagery: Province of Ontario
Short description of collection: 2015 aerial imagery captured as a part of the province of Ontario SWOOP program.
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment]
@CanopyMappingCo Thanks for contributing. A token was sent to the email provided.

**Comment by MDhald** [comment]
@smit1678 I am getting an error waiting for the upload. Any suggestions?
https://upload.openaerialmap.org/#/status/59de204123c8440011d7b2a8
![sad](https://user-images.githubusercontent.com/12298970/34540416-7b634a78-f0a2-11e7-9ce4-68b6c9f270b5.JPG)
